"""GeminiProvider — LLMProvider implementation backed by Google Gemini.

Wraps the ``google-genai`` SDK's async generation endpoint behind the
``LLMProvider`` protocol so that services never import from ``google.genai``
directly.

Model default: ``gemini-2.0-flash`` — Google's fastest capable model,
suitable as a cost-effective fallback for the 2-sentence reasoning
explanations and WhatsApp replies generated by the Aetherix backend.

Activation (no code change required):
    Set ``LLM_BACKEND=gemini`` in the environment. The factory will
    instantiate this provider instead of ``ClaudeProvider``.

Lazy key validation:
    Follows the same pattern as ``ClaudeProvider`` — no exception at
    instantiation time when ``GEMINI_API_KEY`` is absent. The
    ``RuntimeError`` is raised only when ``complete()`` is first called,
    so the app can start cleanly without a live key.
"""
from __future__ import annotations

import os

from app.providers.base import LLMProvider  # noqa: F401 — satisfies Protocol


def _to_gemini_contents(messages: list[dict]) -> list[dict]:
    """Convert OpenAI-style messages to Gemini ``contents`` format.

    Gemini uses ``"model"`` for the assistant role; all other roles map to
    ``"user"``.  Each part is a ``{"text": ...}`` dict.
    """
    result = []
    for m in messages:
        role = "model" if m.get("role") == "assistant" else "user"
        result.append({"role": role, "parts": [{"text": m.get("content", "")}]})
    return result


class GeminiProvider:
    """Wraps ``google.genai.Client.aio.models.generate_content`` behind ``LLMProvider``.

    Args:
        api_key: Gemini API key. Falls back to ``GEMINI_API_KEY`` env var.
        model:   Gemini model ID. Defaults to ``gemini-2.0-flash``.
    """

    def __init__(
        self,
        api_key: str = "",
        model: str = "gemini-2.0-flash",
    ) -> None:
        self._api_key = api_key or os.getenv("GEMINI_API_KEY", "")
        self._model = model
        self._client = None
        if self._api_key:
            from google import genai

            self._client = genai.Client(api_key=self._api_key)

    # ------------------------------------------------------------------
    # LLMProvider protocol
    # ------------------------------------------------------------------

    async def complete(
        self,
        messages: list[dict],
        max_tokens: int = 500,
        temperature: float = 0.3,
        system: str | None = None,
    ) -> str:
        """Call Gemini and return the plain-text completion.

        Args:
            messages:    OpenAI-style message list (role + content dicts).
            max_tokens:  Maximum tokens to generate (``max_output_tokens``).
            temperature: Sampling temperature.
            system:      Optional system instruction; maps to Gemini's
                         ``system_instruction`` config field.

        Returns:
            The model's text response.

        Raises:
            RuntimeError: If ``GEMINI_API_KEY`` is not set when the method
                          is called (lazy validation — not raised at init).
        """
        if self._client is None:
            key = os.getenv("GEMINI_API_KEY", "")
            if not key:
                raise RuntimeError(
                    "GEMINI_API_KEY not set — cannot call GeminiProvider.complete()"
                )
            self._api_key = key
            from google import genai

            self._client = genai.Client(api_key=key)

        from google.genai import types

        config_kwargs: dict = {
            "max_output_tokens": max_tokens,
            "temperature": temperature,
        }
        if system is not None:
            config_kwargs["system_instruction"] = system

        config = types.GenerateContentConfig(**config_kwargs)
        contents = _to_gemini_contents(messages)

        response = await self._client.aio.models.generate_content(
            model=self._model,
            contents=contents,
            config=config,
        )
        return response.text

    @property
    def model_id(self) -> str:
        return f"gemini/{self._model}"
